language: objective-c
before_install:
    - export LANG=en_US.UTF-8
    - gem install cocoapods xcpretty -N
    - cd Example && pod install
    - cd ..
    - set -o pipefail
script: xcodebuild -workspace Example/DBGHTMLEntitiesExample.xcworkspace -scheme DBGHTMLEntitiesExample -sdk iphonesimulator -configuration Debug test | xcpretty -c
