language: objective-c
before_install:
    - export LANG=en_US.UTF-8
    - gem install cocoapods -N
    - cd Example && pod install
    - cd ..
script: xctool -workspace Example/DBGHTMLEntitiesExample.xcworkspace -scheme DBGHTMLEntitiesExample -sdk iphonesimulator test
