language: objective-c
before_install:
    - export LANG=en_US.UTF-8
    - bundle install
    - pod install --project-directory=Example
script:
- set -o pipefail
- xcodebuild -workspace Example/DBGHTMLEntitiesExample.xcworkspace -scheme DBGHTMLEntitiesExample -sdk iphonesimulator -configuration Debug test -destination platform='iOS Simulator',OS='11.4',name='iPhone X' | xcpretty -c
- pod lib lint
