language: objective-c
before_install:
    - export LANG=en_US.UTF-8
    - bundle install
    - pod install --project-directory=Example
    - set -o pipefail
script: xcodebuild -workspace Example/DBGHTMLEntitiesExample.xcworkspace -scheme DBGHTMLEntitiesExample -sdk iphonesimulator -configuration Debug test -destination platform='iOS Simulator',OS='10.0',name='iPhone 7' | xcpretty -c
